### ISSUE TITLE
Brother I have Routing Issue in The Cloned Project while Running

### ISSUE THREAD

**Issue by StealthSkynet** [WebdeveloperIsaac/reactcapstone#1]
While
![IMG_20220807_133940](https://user-images.githubusercontent.com/110759663/183281729-0a4abb86-d5c7-42b5-a217-3da4e30cd6d6.png)
 Running the Project After 
npm install and In Npm run I get blank page and when I look through Console 
I have the following issue in image Can you give a solution?

**Comment by isaac-rnd** [comment]
It's Just a Common Issue Brother i Have Used the React Router Dom version 6 so just 
npm install react-router-dom@latest
This will resolve it cheers👍
