### ISSUE TITLE
React Router v6 Blank Screen Console Routing Error

### ISSUE THREAD

**Issue by StealthSkynet** [WebdeveloperIsaac/reactcapstone#2]
Brother @WebdeveloperIsaac  Even After I upgraded to the newer react Router Version the problem persists
![IMG_20220807_133940](https://user-images.githubusercontent.com/110759663/183296953-f88c6cba-edba-40bf-8c22-1d4a9811e340.png)

**Comment by isaac-rnd** [comment]
Bro You After updating also need to configure the code for the newer version so many tags also changeed in new version k thats why change these tags 
Update all <Router> elements to <Routes>
Change <RouteElement default/> to <RouteElement path="*" />
Fix <Redirect />
Implement <Link getProps /> with hooks
Update useMatch, params are on match.params
Change ServerLocation to StaticRouter
for even more info go through this Article You'll be Fine
[](https://reactrouter.com/docs/en/v6/upgrading/reach)
